apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-gemma-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-gemma-chat
  template:
    metadata:
      labels:
        app: llm-gemma-chat
    spec:
      containers:
      - name: llm-gemma-chat
        image: geethanarasimha/llm-gemma-chat:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
        command: [ "python3", "chat2.py" ]
        # If you want this to interact with Ollama on localhost,
        # make sure Ollama is running in the same pod or as a service


