apiVersion: v1
kind: Service
metadata:
  name: llm-gemma-service
spec:
  selector:
    app: llm-gemma-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
  type: ClusterIP
